services:
  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASS}
    env_file:
      - ./.env 
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"       # expose container's port 80 on host 3000
    depends_on:
      - backend

