name: Flask Backend CI - Dev

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        pip install -r requirements.txt
        pip install ruff pytest

    - name: Lint with ruff
      working-directory: ./backend
      run: |
        ruff check .

    - name: Run unit tests (pytest)
      working-directory: ./backend
      run: |
        pytest
  
  backend-cd:
    runs-on: ubuntu-latest
    environment: dev
    needs: backend-ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get Cloud SQL Connection Name
        run: |
          INSTANCE_ID=$(echo "${{ secrets.CLOUD_SQL_INSTANCE_ID_DEV }}" | cut -d':' -f3)
          INSTANCE_CONNECTION_NAME=$(gcloud sql instances describe "$INSTANCE_ID" --project "${{ secrets.GCP_PROJECT_ID }}" --format='value(connectionName)')
          echo "CLOUD_SQL_CONNECTION_NAME=$INSTANCE_CONNECTION_NAME" >> $GITHUB_ENV

      - name: Install Cloud SQL Proxy
        run: |
          wget https://storage.googleapis.com/cloudsql-proxy/v1.33.3/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy

      - name: Start Cloud SQL Proxy
        run: |
          ./cloud_sql_proxy --address 0.0.0.0 --port 5432 ${{ env.CLOUD_SQL_CONNECTION_NAME }} &
          echo "Cloud SQL Proxy started in the background"
          sleep 5 # Give the proxy a moment to start

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Flask-Migrate

      - name: Configure Flask Environment
        working-directory: ./backend
        run: |
          echo "FLASK_ENV=development" >> $GITHUB_ENV
          echo "DEV_DB_URI=postgresql://${{ secrets.CLOUD_SQL_USERNAME_DEV }}:${{ secrets.CLOUD_SQL_PASSWORD_DEV }}@127.0.0.1:5432/${{ secrets.CLOUD_SQL_DATABASE_DEV }}" >> $GITHUB_ENV

      - name: Run Flask Migrations
        working-directory: ./backend
        run: |
          flask db upgrade

      - name: Stop Cloud SQL Proxy
        run: |
          pkill cloud_sql_proxy